Validat epackage version when building tag

diff --git a/ci/build_dist.yml b/ci/build_dist.yml
--- a/ci/build_dist.yml
+++ b/ci/build_dist.yml
@@ -1,7 +1,14 @@
 build_dist:
   stage: build
   script:
-    - "[ $CI_COMMIT_REF_NAME = master ] && poetry version $(poetry version | cut -d' ' -f2)+$(date +%s).${CI_COMMIT_SHORT_SHA}"
+    - if [ $CI_COMMIT_REF_NAME = master ]; then
+       poetry version $(poetry version | cut -d" " -f2)+$(date +%s).${CI_COMMIT_SHORT_SHA}
+      elif [ x$CI_OMMIT_REF_NAME = x$CI_COMMIT_TAG ]; then
+       if ! [ "$(poetry version | cut -d" " -f2)" = $CI_COMMIT_REF_NAME ]; then
+        echo "Package version does not match tag. Aborting build of tag!" >/dev/fd/2
+	exit 1
+       fi
+      fi
     - tox -e build
     - poetry publish -r gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN} -u gitlab-ci-token
   artifacts:
